# Generated by Django 3.2.9 on 2022-01-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
    ]
